### PR TITLE
Added home page

### PR DESCRIPTION
**Pull request by trilq**
Added home page. Pls review asap.

### CODE REVIEW

**Comment by trilequang** [comment]
It looks simplistic. Pls spice up a bit :smile_cat:

**Comment by trilq** [comment]
What do you mean by "looks simplistic" ? :angry:

**Comment by trilq** [comment]
It lacks of details.

**Comment by trilequang** [comment]
Have added more details to the home page. Pls review again.

**Comment by trilq** [comment]
Have added details to the home page. Pls review it again.

**Comment by trilequang** [comment]
It looks ok now. I merge the pull request.

**Pull request merged**
